### ISSUE TITLE
[Feature request] Make folder icons adjustable

### ISSUE THREAD

**Issue by Speravir** [aaFn/Bookmark-search-plus-2#112]
As mentioned in #111 I use for over one year a user style created by Aris, cf. [this comment](https://github.com/Aris-t2/CustomCSSforFx/issues/109#issuecomment-402849175) (I made an update after a code change), but probably it would be better to provide an opportunity from the addon itself to choose another folder icon – or at least make it easier than now.

A potential problem is that the used symbols are in PNG format (it works fine for me), but if alternative icons were provided, they should probably be better in SVG format. There are lots of free SVG resources out there …

This is the recent code I use. Note, that the file paths are idividual:
```css
div.bkmkitem_f .ffavicon {
	-moz-padding-start: 20px !important;
	background: -moz-image-rect(url("./CustomCSSforFx/image/folder-item.png"), 0, 32, 16, 16) center no-repeat !important;
}

div.bkmkitem_f img[src="/icons/menubkmk.png"] {
	-moz-padding-start: 20px !important;
	background: -moz-image-rect(url("./CustomCSSforFx/image/bookmarksMenu.png"), 0, 16, 16, 0) center no-repeat !important;
}

div.bkmkitem_f img[src="/icons/otherbkmk.png"] {
	-moz-padding-start: 20px !important;
	background: -moz-image-rect(url("./CustomCSSforFx/image/unsortedBookmarks.png"), 0, 16, 16, 0) center no-repeat !important;
}

div.bkmkitem_f img[src="/icons/toolbarbkmk.png"] {
	-moz-padding-start: 20px !important;
	background: -moz-image-rect(url("./CustomCSSforFx_(Aris)/image/bookmarksToolbar.png"), 0, 16, 16, 0) center no-repeat !important;
}
```
