### ISSUE TITLE
Low priority Feature req.: Apply FF theme (dark) to "Bookmark History.." popup

### ISSUE THREAD

**Issue by peter-lyons-kehl** [aaFn/Bookmark-search-plus-2#311]
Even with Options > "Match active FF theme colors", `sidebar/history.html` is mostly black-on-white. If easy, please apply FF theme here, too. (I did **not** try override for this.)

Workaround in the meantime:
1. toolbar > right click > "Open BSP2 in a Tab" > change "sidebar/panel.html" in the URL to "sidebar/history.html"
2. create/locate `userContent.css` for your Firefox profile (steps for this are out of scope here). Add:
```css
/** Some of the following may be unnecessary. */
@-moz-document url-prefix("moz-extension://long-uuid-for-your-firefox_profile/sidebar/history.html") {
  html *,
  body *,
  table#ndtable
  * {
    color: white !important;
    background-color: black !important;
  }
}
```
3. Restart Firefox.
